name: Deploy Firebase Functions

on:
  push:
    branches:
      - staging
      - main
    paths:
      - 'functions/**'
      - '.github/workflows/deploy-functions.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
        
      - name: Install Dependencies
        working-directory: ./functions
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Deploy to Staging
        if: github.ref == 'refs/heads/staging'
        working-directory: ./functions
        run: firebase deploy --only functions --project staging
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          
      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        working-directory: ./functions
        run: firebase deploy --only functions --project production
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}