name: Deploy Firebase Functions

on:
  push:
    branches:
      - staging
      - main
    paths:
      - 'functions/**'
      - '.github/workflows/deploy-functions.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Verify Directory Structure
        run: |
          ls -la
          ls -la functions/

      - name: Create and Setup Virtual Environment
        working-directory: ./functions
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install firebase-functions firebase-admin
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          fi
          
      - name: Deploy to Staging
        if: github.ref == 'refs/heads/staging'
        working-directory: ./functions
        run: |
          source venv/bin/activate
          echo '${{ secrets.STAGING_SERVICE_ACCOUNT }}' > /tmp/staging-service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/staging-service-account.json
          firebase deploy --only functions --project staging
          rm /tmp/staging-service-account.json
          
      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        working-directory: ./functions
        run: |
          source venv/bin/activate
          echo '${{ secrets.PRODUCTION_SERVICE_ACCOUNT }}' > /tmp/production-service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/production-service-account.json
          firebase deploy --only functions --project production
          rm /tmp/production-service-account.json